device: "cuda:0"
results_dir: "./results/hamiltonian_nocarbons"
trained_model_path: null
dataset:
  train_split_ratio: 0.90
  # test_split_ratio: 0.50
  n_atoms_paths: null # Write dataset subfolders suffix. E.g. ["64_ATOMS"]
  stratify: true # set to false if max_samples < 200
  max_samples: null
  seed: 42
  num_unique_z: 2 # Fasten the basis calculation

orbitals:
  1: 13
  2: 13
  3: 13
  4: 13
  5: 13
  6: 13
  7: 13
  8: 13

environment_representation:
  num_interactions: 2 # Nº layers
  correlation: 3 # Correlation order of the messages
  max_ell: 3 # Expansion order

  num_channels: 128 # default. Determines the size of the model
  max_L: 4 # default. Symmetries of the message. According to hidden_irreps.
  r_max: 10.0 # Cutoff radius
  num_elements: 2 # Nº of chemical elements
  atomic_energies: [0, 0] # For normalization(?). torhc.tensor() # Must match the shape of atomic_numbers
  avg_num_neighbors: 8 # For norm.(?)
  atomic_numbers: [5,7] # (?)

  num_bessel: 15 # Nº radial feats
  num_polynomial_cutoff: 8 # Smothness of the radial cutoff
  hidden_irreps: "10x0e + 10x1o + 10x2e + 10x3o"
  MLP_irreps: 20x0e # Nº hidden dim. of last layer readout MLP
  gate: silu # non-linearity of the last layer readout

model:
  readout_per_interaction: false
  preprocessing_nodes: E3nnInteraction
  preprocessing_edges: E3nnEdgeMessageBlock
  node_operation: E3nnSimpleNodeBlock
  edge_operation: E3nnSimpleEdgeBlock
  hidden_neurons: [64, 64, 64, 64]

optimizer:
  lr: 1e-3
  weight_decay: 1e-4

scheduler:
  t_0: 20
  t_multiplication: 2
  eta_min: 1e-25

trainer:
  batch_size: 50
  checkpoint_freq: 500
  exclude_carbons: true

  live_plot: true
  live_plot_freq: 1

  live_plot_matrix: true
  live_plot_matrix_freq: 1000
  live_plot_matrices_num: 1

  num_epochs: 50000
  loss_function: block_type_mse # elementwise_mse, block_type_mse, block_type_mse_threshold

  keep_in_memory: true
  rotating_pool: false
  rotating_pool_size: 400

  matrix: hamiltonian # "hamiltonian", "tim", "overlap"
  
